import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/components/layouts/Layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>NEC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="page_header_default style_one">
          <div className="parallax_cover">
            <div className="simpleParallax">
              <img
                src="../assets/images/page-header-default.jpg"
                alt="bg_image"
                className="cover-parallax"
              />
            </div>
          </div>
          <div className="page_header_content">
            <div className="auto-container">
              <div className="row">
                <div className="col-md-12">
                  <div className="banner_title_inner">
                    <div
                      className="title_page"
                      style={{ fontSize: 30, lineHeight: 1.5 }}
                    >
                      FORMULAİRE D'İDENTİFİCATİON DES ENTRİPRİSES DEVANT
                      ACCOMPAGNER SEM PRESİDENT DE LA REPUBLİQUE A LA COP 28
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="site-content" style={{ backgroundColor: "#f0ebf8" }}>
          <div className="container">
            <div className="ow default_row">
              <div className="full_width_box">
                <div className="pd_top_80"></div>
                
                <section className="col-xl-8 col-lg-6 mb-5 mb-lg-5 mb-xl-0 contact_form_box_all type_one" style={{ margin: "auto auto 1rem auto !important" }}>
                  <div className="contact_form_box_inner">
                    <div className="contact_form_shortcode">
                      <div className="heading" style={{ marginBottom: "2rem" }}>
                        <h2>Contact</h2>
                      </div>

                      <div role="form" className="wpcf7">
                        <form
                          action="#"
                          method="post"
                          className="wpcf7-form init"
                        >
                          <p>
                            <label>
                              NOMS
                              <br />
                              <span className="wpcf7-form-control-wrap your-name">
                                <input
                                  type="text"
                                  name="name"
                                  value=""
                                  size={40}
                                  className="wpcf7-form-control wpcf7-text wpcf7-validates-as-required"
                                  aria-required="true"
                                  aria-invalid="false"
                                  placeholder="saisissez votre nom"
                                />
                              </span>
                              <br />
                              <i className="fa fa-user"></i>
                              <br />
                            </label>
                          </p>
                          <p>
                            <label>
                              POST NOM
                              <br />
                              <span className="wpcf7-form-control-wrap your-email">
                                <input
                                  type="text"
                                  name="middle-name"
                                  value=""
                                  size={40}
                                  className="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email"
                                  aria-required="true"
                                  aria-invalid="false"
                                  placeholder="saisissez votre Post nom "
                                />
                              </span>
                              <br />
                              <i className="fa fa-user"></i>
                              <br />
                            </label>
                          </p>
                          <p>
                            <label>
                              PRENOM
                              <br />
                              <span className="wpcf7-form-control-wrap your-email">
                                <input
                                  type="text"
                                  name="middle-name"
                                  value=""
                                  size={40}
                                  className="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email"
                                  aria-required="true"
                                  aria-invalid="false"
                                  placeholder="saisissez votre Prénom "
                                />
                              </span>
                              <br />
                              <i className="fa fa-user"></i>
                              <br />
                            </label>
                          </p>
                          <p>
                            <label>
                              NATİONALİTE
                              <br />
                              <span className="wpcf7-form-control-wrap your-email">
                                <input
                                  type="text"
                                  name="middle-name"
                                  value=""
                                  size={40}
                                  className="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email"
                                  aria-required="true"
                                  aria-invalid="false"
                                  placeholder="saisissez votre Nationalité  "
                                />
                              </span>
                              <br />
                              <i className="fa fa-user"></i>
                              <br />
                            </label>
                          </p>
                          <p>
                            <label>
                              NUMERO DE TELEPHONE
                              <br />
                              <span className="wpcf7-form-control-wrap your-email">
                                <input
                                  type="text"
                                  name="middle-name"
                                  value=""
                                  size={40}
                                  className="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email"
                                  aria-required="true"
                                  aria-invalid="false"
                                  placeholder="saisissez votre numéro de téléphone  "
                                />
                              </span>
                              <br />
                              <i className="fa fa-user"></i>
                              <br />
                            </label>
                          </p>
                          <p>
                            <label>
                              EMAİL
                              <br />
                              <span className="wpcf7-form-control-wrap your-email">
                                <input
                                  type="mail"
                                  name="middle-name"
                                  value=""
                                  size={40}
                                  className="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email"
                                  aria-required="true"
                                  aria-invalid="false"
                                  placeholder="saisissez votre adresse email  "
                                />
                              </span>
                              <br />
                              <i className="fa fa-user"></i>
                              <br />
                            </label>
                          </p>
                          <p>
                            <label>
                              ADRESSE
                              <br />
                              <span className="wpcf7-form-control-wrap your-email">
                                <input
                                  type="text"
                                  name="middle-name"
                                  value=""
                                  size={40}
                                  className="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email"
                                  aria-required="true"
                                  aria-invalid="false"
                                  placeholder="saisissez votre adresse  "
                                />
                              </span>
                              <br />
                              <i className="fa fa-user"></i>
                              <br />
                            </label>
                          </p>
                        </form>
                      </div>
                    </div>
                  </div>
                </section>

                <section className="col-xl-8 col-lg-6 mb-5 mb-lg-5 mb-xl-0 contact_form_box_all type_one" style={{ margin: "auto auto 1rem auto !important" }}>
                  <div className="contact_form_box_inner">
                    <div className="contact_form_shortcode">
                      <div className="heading" style={{ marginBottom: "2rem" }}>
                        <h2>Qui êtes vous?</h2>
                      </div>

                   

                      <div role="form" className="wpcf7">
                        <form
                          action="#"
                          method="post"
                          className="wpcf7-form init"
                        >
                          <p>
                            <label>
                              NOMS
                              <br />
                              <span className="wpcf7-form-control-wrap your-name">
                                <input
                                  type="text"
                                  name="name"
                                  value=""
                                  size={40}
                                  className="wpcf7-form-control wpcf7-text wpcf7-validates-as-required"
                                  aria-required="true"
                                  aria-invalid="false"
                                  placeholder="saisissez votre nom"
                                />
                              </span>
                              <br />
                              <i className="fa fa-user"></i>
                              <br />
                            </label>
                          </p>
                          <p>
                            <label>
                              POST NOM
                              <br />
                              <span className="wpcf7-form-control-wrap your-email">
                                <input
                                  type="text"
                                  name="middle-name"
                                  value=""
                                  size={40}
                                  className="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email"
                                  aria-required="true"
                                  aria-invalid="false"
                                  placeholder="saisissez votre Post nom "
                                />
                              </span>
                              <br />
                              <i className="fa fa-user"></i>
                              <br />
                            </label>
                          </p>
                          <p>
                            <label>
                              PRENOM
                              <br />
                              <span className="wpcf7-form-control-wrap your-email">
                                <input
                                  type="text"
                                  name="middle-name"
                                  value=""
                                  size={40}
                                  className="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email"
                                  aria-required="true"
                                  aria-invalid="false"
                                  placeholder="saisissez votre Prénom "
                                />
                              </span>
                              <br />
                              <i className="fa fa-user"></i>
                              <br />
                            </label>
                          </p>
                          <p>
                            <label>
                              NATİONALİTE
                              <br />
                              <span className="wpcf7-form-control-wrap your-email">
                                <input
                                  type="text"
                                  name="middle-name"
                                  value=""
                                  size={40}
                                  className="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email"
                                  aria-required="true"
                                  aria-invalid="false"
                                  placeholder="saisissez votre Nationalité  "
                                />
                              </span>
                              <br />
                              <i className="fa fa-user"></i>
                              <br />
                            </label>
                          </p>
                          <p>
                            <label>
                              NUMERO DE TELEPHONE
                              <br />
                              <span className="wpcf7-form-control-wrap your-email">
                                <input
                                  type="text"
                                  name="middle-name"
                                  value=""
                                  size={40}
                                  className="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email"
                                  aria-required="true"
                                  aria-invalid="false"
                                  placeholder="saisissez votre numéro de téléphone  "
                                />
                              </span>
                              <br />
                              <i className="fa fa-user"></i>
                              <br />
                            </label>
                          </p>
                          <p>
                            <label>
                              EMAİL
                              <br />
                              <span className="wpcf7-form-control-wrap your-email">
                                <input
                                  type="mail"
                                  name="middle-name"
                                  value=""
                                  size={40}
                                  className="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email"
                                  aria-required="true"
                                  aria-invalid="false"
                                  placeholder="saisissez votre adresse email  "
                                />
                              </span>
                              <br />
                              <i className="fa fa-user"></i>
                              <br />
                            </label>
                          </p>
                          <p>
                            <label>
                              ADRESSE
                              <br />
                              <span className="wpcf7-form-control-wrap your-email">
                                <input
                                  type="text"
                                  name="middle-name"
                                  value=""
                                  size={40}
                                  className="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email"
                                  aria-required="true"
                                  aria-invalid="false"
                                  placeholder="saisissez votre adresse  "
                                />
                              </span>
                              <br />
                              <i className="fa fa-user"></i>
                              <br />
                            </label>
                          </p>

                          <p>
                            <input
                              type="submit"
                              value="Submit"
                              className="wpcf7-form-control has-spinner wpcf7-submit"
                            />
                          </p>
                        </form>
                      </div>


                    </div>
                  </div>
                </section>

              </div>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}
