import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/components/layouts/Layout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>NEC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* <!---slider--> */}
        <section className="slider style_four nav_position_one">
          <div
            className="owl-carousel owl_nav_block owl_dots_none theme_carousel owl-theme"
            data-options='{"loop": true, "margin": 0, "autoheight":true, "lazyload":true, "nav": true, "dots": true, "autoplay": true, "autoplayTimeout": 7000, "smartSpeed": 1800, "responsive":{ "0" :{ "items": "1" }, "768" :{ "items" : "1" } , "1000":{ "items" : "1" }}}'
          >
            <div className="slide-item-content">
              <div className="slide-item content_left">
                <div
                  className="image-layer"
                  style={{
                    backgroundImage: "url(/images/sliders/slider-1-1.jpg)",
                  }}
                ></div>
                <div className="auto-container">
                  <div className="row">
                    <div className="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                      <div className="slider_content pd_top_180 pd_bottom_200">
                        <h6 className="animate_up d-inline-block">
                          Our Vision to Grow Better
                        </h6>
                        <h1 className="animate_left">
                          Inspired <br /> Performance
                        </h1>
                        <p className="description animate_right">
                          Duty obligations of business it will frequently occur
                          that pleasures <br /> have to be repudiated and
                          annoyances accepted.
                        </p>
                        <div className="button_all animate_down">
                          <a
                            href="#"
                            target="_blank"
                            rel="nofollow"
                            className="theme-btn one  animated"
                          >
                            Read More
                          </a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* <!---slider-end---> */}

        <section className="image-box-section">
          <div className="pd_top_80"></div>
          <div className="container">
            <div className="row">
              <div className="col-xl-6 col-lg-12 mb-5 mb-lg-5 mb-xl-0">
                <div className="image_boxes style_three">
                  <img
                    src="/images/about/about-8.jpg"
                    className="img-fluid height_500 object-fit-cover"
                    alt="image"
                  />
                  <div className="video_box">
                    <a
                      href="https://www.youtube.com/embed/-VK0axfge4A"
                      className="lightbox-image"
                    >
                      <i className="icon-play"></i>
                    </a>
                  </div>
                </div>
              </div>
              <div className="col-xl-6 col-lg-12">
                <div className="title_all_box style_one dark_color">
                  <div className="title_sections ">
                    <div className="before_title">Évenement </div>
                    <h2>Professional Individuals</h2>

                    <p>
                      Our power of choice is untrammelled and when nothing
                      prevents being able to do what we like best every
                      pleasure.
                    </p>
                  </div>
                </div>
                <div className="progress_bar style_two">
                  <div className="progress_new">
                    <div
                      className="ProgressBar ProgressBar--animateText"
                      data-progress="84"
                    >
                      <svg
                        className="ProgressBar-contentCircle"
                        height="170"
                        width="170"
                      >
                        <circle
                          className="ProgressBar-background"
                          cx="85"
                          cy="85"
                          r="75"
                        ></circle>
                        <circle
                          transform="rotate(-90, 85, 85)"
                          className="ProgressBar-circle"
                          cx="85"
                          cy="85"
                          r="75"
                          style={{
                            strokeDasharray: "471px",
                            strokeDashoffset: "75.36px",
                          }}
                        ></circle>
                      </svg>
                    </div>
                    <div className="progress-value">
                      <div>
                        <h6>Year of 2020 </h6>
                      </div>
                    </div>
                  </div>
                  <div className="content_box">
                    <h2>84%</h2>
                    <h3>Income Statement </h3>
                    <p>
                      Certain circumstances seds owing to the claims duty
                      righteous indignation and so beguiled.{" "}
                    </p>
                  </div>
                </div>
                <div className="pd_top_30"></div>
                <div className="row">
                  <div className="col-lg-4 col-md-4 col-sm-12">
                    <div className="theme_btn_all color_one">
                      <a
                        href="#"
                        target="_blank"
                        rel="nofollow"
                        className="theme-btn one"
                      >
                        Download
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="pd_bottom_80"></div>
        </section>

        <section className="service_section bg_light_1" id="service">
          <div className="pd_top_80"></div>
          <div className="container">
            <div className="row">
              <div className="title_all_box style_one text-center dark_color">
                <div className="title_sections">
                  <h2>SERVICES</h2>
                </div>
              </div>
              <div className="pd_bottom_20"></div>
              <div className="col-xl-4 col-lg-6 col-md-12 col-sm-12 col-xs-12">
                <div className="service_box style_two dark_color">
                  <div className="service_content_two ">
                    <div
                      className="content_inner"
                      style={{
                        backgroundImage:
                          "url(/images/service/service-image-1.png)",
                      }}
                    >
                      <div className="content_inner_in">
                        <div className="icon_image">
                          <img
                            src="/images/010-job-search.png"
                            className="img-fluid"
                            alt="Service Image"
                          />
                        </div>
                        <h2>
                          <a href="#">Recruitment Process</a>
                        </h2>
                        <p>
                          These cases are perfectly simple and easy to
                          distinguish.
                        </p>
                        <ul>
                          <li>Reducing Redundancy</li>
                          <li>Uncovering Hidden Resources</li>
                          <li>Increasing Company’s Agility</li>
                        </ul>
                      </div>
                    </div>
                    <div className="ovarlay_link">
                      <a href="#">
                        <i className="icon-right-arrow"></i>
                      </a>
                    </div>
                    <div className="overlay_content">
                      <h2>
                        <a href="#">Recruitment Process</a>
                      </h2>
                      <p>
                        These cases are perfectly simple and easy to
                        distinguish.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="mr_bottom_20"></div>
              </div>
              <div className="col-xl-4 col-lg-6 col-md-12 col-sm-12 col-xs-12">
                <div className="service_box style_two dark_color">
                  <div className="service_content_two  active_ser">
                    <div
                      className="content_inner"
                      style={{
                        backgroundImage:
                          "url(/images/service/service-image-2.png)",
                      }}
                    >
                      <div className="content_inner_in">
                        <div className="icon_image">
                          <img
                            src="/images/service-ico-1.png"
                            className="img-fluid"
                            alt="Service Image"
                          />
                        </div>
                        <h2>
                          <a href="#">Employee Relations</a>
                        </h2>
                        <p>
                          Indignation sed dislike men who are beguiled and
                          demoralized.
                        </p>
                        <ul>
                          <li>Improving Communication</li>
                          <li>Employee issue resolution</li>
                          <li>Proper Documentation Process</li>
                        </ul>
                      </div>
                    </div>
                    <div className="ovarlay_link">
                      <a href="#">
                        <i className="icon-right-arrow"></i>
                      </a>
                    </div>
                    <div className="overlay_content">
                      <h2>
                        <a href="#">Employee Relations</a>
                      </h2>
                      <p>
                        Indignation sed dislike men who are beguiled and
                        demoralized.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="mr_bottom_20"></div>
              </div>
              <div className="col-xl-4 col-lg-6 col-md-12 col-sm-12 col-xs-12">
                <div className="service_box style_two dark_color">
                  <div className="service_content_two ">
                    <div
                      className="content_inner"
                      style={{
                        backgroundImage:
                          "url(/images/service/service-image-3.png)",
                      }}
                    >
                      <div className="content_inner_in">
                        <div className="icon_image">
                          <img
                            src="/images/service-ico-2.png"
                            className="img-fluid"
                            alt="Service Image"
                          />
                        </div>
                        <h2>
                          <a href="#">Compliance Audits</a>
                        </h2>
                        <p>
                          Prevents our being able too what get like best every
                          pleasure.
                        </p>
                        <ul>
                          <li>Handling of employment</li>
                          <li>Greater retention rates</li>
                          <li>A fully engaged workforce</li>
                        </ul>
                      </div>
                    </div>
                    <div className="ovarlay_link">
                      <a href="#">
                        <i className="icon-right-arrow"></i>
                      </a>
                    </div>
                    <div className="overlay_content">
                      <h2>
                        <a href="#">Compliance Audits</a>
                      </h2>
                      <p>
                        Prevents our being able too what get like best every
                        pleasure.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="mr_bottom_20"></div>
              </div>
            </div>
          </div>
          <div className="pd_bottom_70"></div>
        </section>
        {/* <!---blog---> */}
        <section className="blog-post" id="blog">
          <div className="pd_top_80"></div>
          <div className="container">
            <div className="row">
              <div className="col-lg-12">
                <div className="title_all_box style_one text-center  dark_color">
                  <div className="title_sections">
                    <h2>Actualités</h2>
                  </div>
                </div>
                <div className="pd_bottom_20"></div>
              </div>

              <section className="two_column news_wrapper_grid">
                <div className="grid_show_case grid_layout clearfix">
                  <div className="news_box style_two grid_box _card has_images">
                    <div className="content_box">
                      <div className="overlay"> </div>
                      <img
                        src="/images/blog/blog-image-1.jpg"
                        className="img-fluid"
                        alt="img"
                      />
                      <div className="category">
                        <a href="#" className="categories">
                          <i className="icon-folder"></i>Compliance Audits
                        </a>
                      </div>
                      <div className="content_mid">
                        <span className="date_in_number">Oct 06 , 2023</span>
                        <h2 className="title">
                          <a href="blog-single.html">
                            Outsource Accounting &#038; HR Functions
                          </a>
                        </h2>
                      </div>
                      <div className="auhtour_box">
                        <img
                          alt="img"
                          className="img-fluid"
                          src="/images/auth-1.png"
                          height="60"
                          width="60"
                        />
                        <div className="contnet_a">
                          <p>POSTED BY</p>
                          <h4> Evan Thomas </h4>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="news_box style_two grid_box _card has_images">
                    <div className="content_box">
                      <div className="overlay"> </div>
                      <img
                        src="/images//blog/blog-image-11.jpg"
                        className="img-fluid"
                        alt="img"
                      />
                      <div className="category">
                        <a href="#" className="categories">
                          <i className="icon-folder"></i>Coaching
                        </a>
                      </div>
                      <div className="content_mid">
                        <span className="date_in_number">Oct 08 , 2023</span>
                        <h2 className="title">
                          <a href="blog-single.html">
                            Workplace problems in your business?
                          </a>
                        </h2>
                      </div>
                      <div className="auhtour_box">
                        <img
                          alt="img"
                          className="img-fluid"
                          src="/images/auth-2.png"
                          height="60"
                          width="60"
                        />
                        <div className="contnet_a">
                          <p>POSTED BY</p>
                          <h4> Roman Brayden </h4>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
              <section className="four_column news_wrapper_grid">
                <div className="grid_show_case grid_layout clearfix">
                  <div className="news_box style_six grid_box _card has_images">
                    <div className="content_box">
                      <div className="overlay"> </div>
                      <img
                        width="852"
                        height="812"
                        src="/images/blog/blog-image-9.jpg"
                        className="img-fluid"
                        alt="img"
                      />
                      <div className="category">
                        <a href="#" className="categories">
                          <i className="icon-folder"></i>Coaching
                        </a>
                      </div>
                      <div className="content_mid">
                        <span className="date_in_number">Oct 08 , 2023</span>
                        <h2 className="title">
                          <a href="blog-single.html">
                            Why Should Business Payroll Outsourcing?
                          </a>
                        </h2>
                      </div>
                      <div className="auhtour_box">
                        <img
                          alt="img"
                          className="img-fluid"
                          src="/images/auth-2.png"
                          height="60"
                          width="60"
                        />
                        <div className="contnet_a">
                          <p>POSTED BY</p>
                          <h4> Evan Thomas </h4>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="news_box style_six grid_box _card has_images">
                    <div className="content_box">
                      <div className="overlay"> </div>
                      <img
                        width="1047"
                        height="697"
                        src="/images/blog/blog-image-8.jpg"
                        className="img-fluid"
                        alt="img"
                      />
                      <div className="category">
                        <a href="#" className="categories">
                          <i className="icon-folder"></i>HR Consulting
                        </a>
                      </div>
                      <div className="content_mid">
                        <span className="date_in_number">Oct 08 , 2023</span>
                        <h2 className="title">
                          <a href="blog-single.html">
                            Workforce Challenges &#038; Opportunities
                          </a>
                        </h2>
                      </div>
                      <div className="auhtour_box">
                        <img
                          alt="img"
                          className="img-fluid"
                          src="/images/auth-1.png"
                          height="60"
                          width="60"
                        />
                        <div className="contnet_a">
                          <p>POSTED BY</p>
                          <h4> Roman Brayden </h4>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="news_box style_six grid_box _card has_images">
                    <div className="content_box">
                      <div className="overlay"> </div>
                      <img
                        width="1557"
                        height="1038"
                        src="/images/blog/blog-image-7.jpg"
                        className="img-fluid"
                        alt="img"
                      />
                      <div className="category">
                        <a href="#" className="categories">
                          <i className="icon-folder"></i>Compliance Audits
                        </a>
                      </div>
                      <div className="content_mid">
                        <span className="date_in_number">Oct 08 , 2023</span>
                        <h2 className="title">
                          <a href="blog-single.html">
                            How to Handle Your Good Employee
                          </a>
                        </h2>
                      </div>
                      <div className="auhtour_box">
                        <img
                          alt="img"
                          className="img-fluid"
                          src="/images/auth-2.png"
                          height="60"
                          width="60"
                        />
                        <div className="contnet_a">
                          <p>POSTED BY</p>
                          <h4> Evan Thomas </h4>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="news_box style_six grid_box _card has_images">
                    <div className="content_box">
                      <div className="overlay"> </div>
                      <img
                        width="593"
                        height="396"
                        src="/images/blog/blog-image-6.jpg"
                        className="img-fluid"
                        alt="img"
                      />
                      <div className="category">
                        <a href="#" className="categories">
                          <i className="icon-folder"></i>Coaching
                        </a>
                      </div>
                      <div className="content_mid">
                        <span className="date_in_number">Oct 08 , 2023</span>
                        <h2 className="title">
                          <a href="blog-single.html">
                            Retaining Good Employees &#038; Motivated
                          </a>
                        </h2>
                      </div>
                      <div className="auhtour_box">
                        <img
                          alt="img"
                          className="img-fluid"
                          src="/images/auth-2.png"
                          height="60"
                          width="60"
                        />
                        <div className="contnet_a">
                          <p>POSTED BY</p>
                          <h4> Roman Brayden </h4>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
            </div>
          </div>
          <div className="pd_bottom_70"></div>
        </section>
        {/* <!---blog-end---> */}
        {/* <!---project---> */}
        <section className="bg_light_1" id="projects">
          <div className="pd_top_80"></div>
          <div className="container">
            <div className="row">
              <div className="title_all_box style_one text-center dark_color">
                <div className="title_sections">
                  <h2>Projets</h2>
                </div>
                <div className="mr_bottom_10"></div>
              </div>
            </div>
          </div>
          <div className="container">
            <div className="row">
              <div className="col-lg-12">
                <div className="project_caro_section carousel style_one ">
                  <div className="swiper-container">
                    <div className="swiper-wrapper">
                      <div
                        className="swiper-slide swiper-slide-active"
                        role="group"
                        aria-label="8 / 8"
                        data-swiper-slide-index="7"
                        style={{ width: "330px", marginRight: "30px" }}
                      >
                        <div className="project_post style_one mr_top_20">
                          <div className="image">
                            <img
                              src="/images/projects/project-3-img.jpg"
                              className="img-fluid"
                              alt="img"
                            />
                          </div>
                          <div className="project_caro_content">
                            <div className="left_side">
                              <p>Human Resources</p>
                              <h2 className="title_pro">
                                <a href="project-details.html">
                                  Essential Steps to Writing Job Description
                                </a>
                              </h2>
                            </div>
                            <div className="right_side">
                              <a href="project-details.html">
                                <i className="icon-right-arrow"></i>
                              </a>
                              <a href="project-details.html" className="two">
                                <i className="icon-right-arrow"></i>
                              </a>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        className="swiper-slide swiper-slide-active"
                        role="group"
                        aria-label="8 / 8"
                        data-swiper-slide-index="7"
                        style={{ width: "330px", marginRight: "30px" }}
                      >
                        <div className="project_post style_one mr_top_20">
                          <div className="image">
                            <img
                              src="/images/projects/project-3-img.jpg"
                              className="img-fluid"
                              alt="img"
                            />
                          </div>
                          <div className="project_caro_content">
                            <div className="left_side">
                              <p>Human Resources</p>
                              <h2 className="title_pro">
                                <a href="project-details.html">
                                  Essential Steps to Writing Job Description
                                </a>
                              </h2>
                            </div>
                            <div className="right_side">
                              <a href="project-details.html">
                                <i className="icon-right-arrow"></i>
                              </a>
                              <a href="project-details.html" className="two">
                                <i className="icon-right-arrow"></i>
                              </a>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        className="swiper-slide swiper-slide-active"
                        role="group"
                        aria-label="8 / 8"
                        data-swiper-slide-index="7"
                        style={{ width: "330px", marginRight: "30px" }}
                      >
                        <div className="project_post style_one mr_top_20">
                          <div className="image">
                            <img
                              src="/images/projects/project-3-img.jpg"
                              className="img-fluid"
                              alt="img"
                            />
                          </div>
                          <div className="project_caro_content">
                            <div className="left_side">
                              <p>Human Resources</p>
                              <h2 className="title_pro">
                                <a href="project-details.html">
                                  Essential Steps to Writing Job Description
                                </a>
                              </h2>
                            </div>
                            <div className="right_side">
                              <a href="project-details.html">
                                <i className="icon-right-arrow"></i>
                              </a>
                              <a href="project-details.html" className="two">
                                <i className="icon-right-arrow"></i>
                              </a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div className="p_pagination">
                      <div className="swiper-pagination"></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="pd_bottom_90"></div>
        </section>
        {/* <!---project-end---> */}

        <section className="newsteller style_one bg_dark_3">
          <div className="pd_top_40"></div>
          <div className="auto-container">
            <div className="row align-items-center">
              <div className="col-lg-6 col-md-12">
                <div className="content">
                  <h2>Join Our Mailing List</h2>
                  <p>
                    For receiving our news and updates in your inbox directly.{" "}
                  </p>
                </div>
              </div>
              <div className="col-lg-6 col-md-12">
                <div className="item_scubscribe">
                  <div className="input_group">
                    <form
                      className="mc4wp-form"
                      method="post"
                      data-name="Subscibe"
                    >
                      <div className="mc4wp-form-fields">
                        <input
                          type="email"
                          name="EMAIL"
                          placeholder="Votre adresse email"
                          required={true}
                        />
                        <input type="submit" value="S'inscrire" />
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="pd_bottom_40"></div>
        </section>
      </Layout>
    </>
  );
}
