import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/components/layouts/Layout";
import Slider from "@/components/home/Slider";

export default function Home() {
  return (
    <>
      <Head>
        <title>NEC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* <!---slider--> */}
        <Slider />

        <section className="image-box-section">
          <div className="pd_top_80"></div>
          <div className="container">
            <div className="row">
              <div className="col-xl-6 col-lg-12 mb-5 mb-lg-5 mb-xl-0">
                <div className="image_boxes style_three">
                  <img
                    src="/images/fenec.jpeg"
                    className="img-fluid height_500 object-fit-cover"
                    alt="image"
                  />
                  <div className="video_box">
                    <a href="/videos/fenec.mp4" className="lightbox-image">
                      <i className="icon-play"></i>
                    </a>
                  </div>
                </div>
              </div>
              <div className="col-xl-6 col-lg-12">
                <div className="title_all_box style_one dark_color">
                  <div className="title_sections ">
                    <div className="before_title">Évenement </div>
                    <h2>FORUM ÉCONOMIQUE SUR LA NOUVELLE ÉCONOMIE DU CLIMAT</h2>

                    <p>
                      Accompagner le secteur privé congolais à tirer pleinement
                      profit du marché Carbone dans un climat d'affaires de
                      haute integrité
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="pd_bottom_80"></div>
        </section>

        {/* <!---slider-end---> */}
        <section className="expertise">
          <div className="area_of_expertise">
            <div className="simpleParallax">
              <img
                src="/images/event-cover.JPG"
                className="cover-parallax"
                alt="image"
              />
            </div>
            <div className="title_and_video">
              <div className="auto-container">
                <div className="row">
                  <div className="col-lg-4">
                    <div className="video_box text-center">
                      <a href="/videos/fenec.mp4" className="lightbox-image">
                        <i className="icon-play"></i>
                      </a>
                    </div>
                  </div>
                  <div className="col-lg-2"></div>
                  <div className="col-lg-6">
                    <div className="title_all_box style_one text-end">
                      <div className="title_sections">
                        <h2>Crédit-carbone</h2>
                        <p>
                          Un crédit-carbone est un certificat relatif à
                          l'évitement, la réduction ou à l'élimination d'une
                          tonne de dioxyde de carbone, ou son équivalent
                          d'autres gaz à effet de serre. Ces certificats
                          s'inscrivent généralement dans le cadre de mécanismes
                          de marché visant à l'atténuation du changement
                          climatique terrestre.
                        </p>
                      </div>
                      <div className="theme_btn">
                        <a
                          href="service-default.html"
                          className="theme-btn one"
                        >
                          Voir plus
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="expertise">
              <div className="auto-container">
                <div className="row">
                  <div className="col-lg-4 col-md-6 col-sm-12 col-xs-12 expertise_box">
                    <div className="step_number">
                      <h1>01.</h1>
                    </div>
                    <h2 className="title">
                      <a href="#">Modélisation</a>
                    </h2>
                  </div>
                  <div className="col-lg-4 col-md-6 col-sm-12 col-xs-12 expertise_box">
                    <div className="step_number">
                      <h1>02.</h1>
                    </div>
                    <h2 className="title">
                      <a href="#">Arbres et forêts</a>
                    </h2>
                  </div>
                  <div className="col-lg-4 col-md-6 col-sm-12 col-xs-12 expertise_box">
                    <div className="step_number">
                      <h1>03.</h1>
                    </div>
                    <h2 className="title">
                      <a href="#">Utilisation</a>
                    </h2>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section className="service_section bg_light_1" id="service">
          <div className="pd_top_80"></div>
          <div className="container">
            <div className="row">
              <div className="title_all_box style_one text-center dark_color">
                <div className="title_sections">
                  <h2>Opportunités</h2>
                </div>
              </div>

              <div className="pd_bottom_20"></div>

              <div className="col-xl-4 col-lg-6 col-md-12 col-sm-12 col-xs-12">
                <div className="service_box style_two dark_color">
                  <div className="service_content_two ">
                    <div
                      className="content_inner"
                      style={{
                        backgroundImage:
                          "url(/images/service/service-image-1.png)",
                      }}
                    >
                      <div className="content_inner_in">
                        <div className="icon_image">
                          <img
                            src="/images/010-job-search.png"
                            className="img-fluid"
                            alt="Service Image"
                          />
                        </div>
                        <h2>
                          <a href="#">Recruitment Process</a>
                        </h2>
                        <p>
                          These cases are perfectly simple and easy to
                          distinguish.
                        </p>
                        <ul>
                          <li>Reducing Redundancy</li>
                          <li>Uncovering Hidden Resources</li>
                          <li>Increasing Company’s Agility</li>
                        </ul>
                      </div>
                    </div>
                    <div className="ovarlay_link">
                      <a href="#">
                        <i className="icon-right-arrow"></i>
                      </a>
                    </div>
                    <div className="overlay_content">
                      <h2>
                        <a href="#">Recruitment Process</a>
                      </h2>
                      <p>
                        These cases are perfectly simple and easy to
                        distinguish.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="mr_bottom_20"></div>
              </div>
              <div className="col-xl-4 col-lg-6 col-md-12 col-sm-12 col-xs-12">
                <div className="service_box style_two dark_color">
                  <div className="service_content_two  ">
                    <div
                      className="content_inner"
                      style={{
                        backgroundImage:
                          "url(/images/service/service-image-2.png)",
                      }}
                    >
                      <div className="content_inner_in">
                        <div className="icon_image">
                          <img
                            src="/images/service-ico-1.png"
                            className="img-fluid"
                            alt="Service Image"
                          />
                        </div>
                        <h2>
                          <a href="#">Employee Relations</a>
                        </h2>
                        <p>
                          Indignation sed dislike men who are beguiled and
                          demoralized.
                        </p>
                        <ul>
                          <li>Improving Communication</li>
                          <li>Employee issue resolution</li>
                          <li>Proper Documentation Process</li>
                        </ul>
                      </div>
                    </div>
                    <div className="ovarlay_link">
                      <a href="#">
                        <i className="icon-right-arrow"></i>
                      </a>
                    </div>
                    <div className="overlay_content">
                      <h2>
                        <a href="#">Employee Relations</a>
                      </h2>
                      <p>
                        Indignation sed dislike men who are beguiled and
                        demoralized.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="mr_bottom_20"></div>
              </div>
              <div className="col-xl-4 col-lg-6 col-md-12 col-sm-12 col-xs-12">
                <div className="service_box style_two dark_color">
                  <div className="service_content_two ">
                    <div
                      className="content_inner"
                      style={{
                        backgroundImage:
                          "url(/images/service/service-image-3.png)",
                      }}
                    >
                      <div className="content_inner_in">
                        <div className="icon_image">
                          <img
                            src="/images/service-ico-2.png"
                            className="img-fluid"
                            alt="Service Image"
                          />
                        </div>
                        <h2>
                          <a href="#">Compliance Audits</a>
                        </h2>
                        <p>
                          Prevents our being able too what get like best every
                          pleasure.
                        </p>
                        <ul>
                          <li>Handling of employment</li>
                          <li>Greater retention rates</li>
                          <li>A fully engaged workforce</li>
                        </ul>
                      </div>
                    </div>
                    <div className="ovarlay_link">
                      <a href="#">
                        <i className="icon-right-arrow"></i>
                      </a>
                    </div>
                    <div className="overlay_content">
                      <h2>
                        <a href="#">Compliance Audits</a>
                      </h2>
                      <p>
                        Prevents our being able too what get like best every
                        pleasure.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="mr_bottom_20"></div>
              </div>

              <div
                className="theme_btn"
                style={{
                  display: "flex",
                  justifyContent: "center",
                  marginTop: "4rem",
                }}
              >
                <a href="service-default.html" className="theme-btn one">
                  Voir plus
                </a>
              </div>
            </div>
          </div>
          <div className="pd_bottom_70"></div>
        </section>
        {/* <!---blog---> */}

        <section className="blog-post" id="blog">
          <div className="pd_top_80"></div>
          <div className="container">
            <div className="row">
              <div className="col-lg-12">
                <div className="title_all_box style_one text-center  dark_color">
                  <div className="title_sections">
                    <h2>Actualités</h2>
                  </div>
                </div>
                <div className="pd_bottom_20"></div>
              </div>

              <section className="two_column news_wrapper_grid">
                <div className="grid_show_case grid_layout clearfix">
                  <div className="news_box style_two grid_box _card has_images">
                    <div className="content_box">
                      <div className="overlay"> </div>
                      <img
                        src="/images/blog/blog-image-1.jpg"
                        className="img-fluid"
                        alt="img"
                      />
                      <div className="category">
                        <a href="#" className="categories">
                          <i className="icon-folder"></i>Compliance Audits
                        </a>
                      </div>
                      <div className="content_mid">
                        <span className="date_in_number">Oct 06 , 2023</span>
                        <h2 className="title">
                          <a href="blog-single.html">
                            Outsource Accounting &#038; HR Functions
                          </a>
                        </h2>
                      </div>
                      <div className="auhtour_box">
                        <img
                          alt="img"
                          className="img-fluid"
                          src="/images/auth-1.png"
                          height="60"
                          width="60"
                        />
                        <div className="contnet_a">
                          <p>POSTED BY</p>
                          <h4> Evan Thomas </h4>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="news_box style_two grid_box _card has_images">
                    <div className="content_box">
                      <div className="overlay"> </div>
                      <img
                        src="/images//blog/blog-image-11.jpg"
                        className="img-fluid"
                        alt="img"
                      />
                      <div className="category">
                        <a href="#" className="categories">
                          <i className="icon-folder"></i>Coaching
                        </a>
                      </div>
                      <div className="content_mid">
                        <span className="date_in_number">Oct 08 , 2023</span>
                        <h2 className="title">
                          <a href="blog-single.html">
                            Workplace problems in your business?
                          </a>
                        </h2>
                      </div>
                      <div className="auhtour_box">
                        <img
                          alt="img"
                          className="img-fluid"
                          src="/images/auth-2.png"
                          height="60"
                          width="60"
                        />
                        <div className="contnet_a">
                          <p>POSTED BY</p>
                          <h4> Roman Brayden </h4>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
              <section className="four_column news_wrapper_grid">
                <div className="grid_show_case grid_layout clearfix">
                  <div className="news_box style_six grid_box _card has_images">
                    <div className="content_box">
                      <div className="overlay"> </div>
                      <img
                        width="852"
                        height="812"
                        src="/images/blog/blog-image-9.jpg"
                        className="img-fluid"
                        alt="img"
                      />
                      <div className="category">
                        <a href="#" className="categories">
                          <i className="icon-folder"></i>Coaching
                        </a>
                      </div>
                      <div className="content_mid">
                        <span className="date_in_number">Oct 08 , 2023</span>
                        <h2 className="title">
                          <a href="blog-single.html">
                            Why Should Business Payroll Outsourcing?
                          </a>
                        </h2>
                      </div>
                      <div className="auhtour_box">
                        <img
                          alt="img"
                          className="img-fluid"
                          src="/images/auth-2.png"
                          height="60"
                          width="60"
                        />
                        <div className="contnet_a">
                          <p>POSTED BY</p>
                          <h4> Evan Thomas </h4>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="news_box style_six grid_box _card has_images">
                    <div className="content_box">
                      <div className="overlay"> </div>
                      <img
                        width="1047"
                        height="697"
                        src="/images/blog/blog-image-8.jpg"
                        className="img-fluid"
                        alt="img"
                      />
                      <div className="category">
                        <a href="#" className="categories">
                          <i className="icon-folder"></i>HR Consulting
                        </a>
                      </div>
                      <div className="content_mid">
                        <span className="date_in_number">Oct 08 , 2023</span>
                        <h2 className="title">
                          <a href="blog-single.html">
                            Workforce Challenges &#038; Opportunities
                          </a>
                        </h2>
                      </div>
                      <div className="auhtour_box">
                        <img
                          alt="img"
                          className="img-fluid"
                          src="/images/auth-1.png"
                          height="60"
                          width="60"
                        />
                        <div className="contnet_a">
                          <p>POSTED BY</p>
                          <h4> Roman Brayden </h4>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="news_box style_six grid_box _card has_images">
                    <div className="content_box">
                      <div className="overlay"> </div>
                      <img
                        width="1557"
                        height="1038"
                        src="/images/blog/blog-image-7.jpg"
                        className="img-fluid"
                        alt="img"
                      />
                      <div className="category">
                        <a href="#" className="categories">
                          <i className="icon-folder"></i>Compliance Audits
                        </a>
                      </div>
                      <div className="content_mid">
                        <span className="date_in_number">Oct 08 , 2023</span>
                        <h2 className="title">
                          <a href="blog-single.html">
                            How to Handle Your Good Employee
                          </a>
                        </h2>
                      </div>
                      <div className="auhtour_box">
                        <img
                          alt="img"
                          className="img-fluid"
                          src="/images/auth-2.png"
                          height="60"
                          width="60"
                        />
                        <div className="contnet_a">
                          <p>POSTED BY</p>
                          <h4> Evan Thomas </h4>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="news_box style_six grid_box _card has_images">
                    <div className="content_box">
                      <div className="overlay"> </div>
                      <img
                        width="593"
                        height="396"
                        src="/images/blog/blog-image-6.jpg"
                        className="img-fluid"
                        alt="img"
                      />
                      <div className="category">
                        <a href="#" className="categories">
                          <i className="icon-folder"></i>Coaching
                        </a>
                      </div>
                      <div className="content_mid">
                        <span className="date_in_number">Oct 08 , 2023</span>
                        <h2 className="title">
                          <a href="blog-single.html">
                            Retaining Good Employees &#038; Motivated
                          </a>
                        </h2>
                      </div>
                      <div className="auhtour_box">
                        <img
                          alt="img"
                          className="img-fluid"
                          src="/images/auth-2.png"
                          height="60"
                          width="60"
                        />
                        <div className="contnet_a">
                          <p>POSTED BY</p>
                          <h4> Roman Brayden </h4>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
            </div>
          </div>
          <div className="pd_bottom_70"></div>
        </section>
        {/* <!---blog-end---> */}
        {/* <!---project---> */}
        {/* <section className="bg_light_1" id="projects">
          <div className="pd_top_80"></div>
          <div className="container">
            <div className="row">
              <div className="title_all_box style_one text-center dark_color">
                <div className="title_sections">
                  <h2>Projets</h2>
                </div>
                <div className="mr_bottom_10"></div>
              </div>
            </div>
          </div>
          <div className="container">
            <div className="row">
              <div className="col-lg-12">
                <div className="project_caro_section carousel style_one ">
                  <div className="swiper-container">
                    <div className="swiper-wrapper">
                      <div
                        className="swiper-slide swiper-slide-active"
                        role="group"
                        aria-label="8 / 8"
                        data-swiper-slide-index="7"
                        style={{ width: "330px", marginRight: "30px" }}
                      >
                        <div className="project_post style_one mr_top_20">
                          <div className="image">
                            <img
                              src="/images/projects/project-3-img.jpg"
                              className="img-fluid"
                              alt="img"
                            />
                          </div>
                          <div className="project_caro_content">
                            <div className="left_side">
                              <p>Human Resources</p>
                              <h2 className="title_pro">
                                <a href="project-details.html">
                                  Essential Steps to Writing Job Description
                                </a>
                              </h2>
                            </div>
                            <div className="right_side">
                              <a href="project-details.html">
                                <i className="icon-right-arrow"></i>
                              </a>
                              <a href="project-details.html" className="two">
                                <i className="icon-right-arrow"></i>
                              </a>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        className="swiper-slide swiper-slide-active"
                        role="group"
                        aria-label="8 / 8"
                        data-swiper-slide-index="7"
                        style={{ width: "330px", marginRight: "30px" }}
                      >
                        <div className="project_post style_one mr_top_20">
                          <div className="image">
                            <img
                              src="/images/projects/project-3-img.jpg"
                              className="img-fluid"
                              alt="img"
                            />
                          </div>
                          <div className="project_caro_content">
                            <div className="left_side">
                              <p>Human Resources</p>
                              <h2 className="title_pro">
                                <a href="project-details.html">
                                  Essential Steps to Writing Job Description
                                </a>
                              </h2>
                            </div>
                            <div className="right_side">
                              <a href="project-details.html">
                                <i className="icon-right-arrow"></i>
                              </a>
                              <a href="project-details.html" className="two">
                                <i className="icon-right-arrow"></i>
                              </a>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        className="swiper-slide swiper-slide-active"
                        role="group"
                        aria-label="8 / 8"
                        data-swiper-slide-index="7"
                        style={{ width: "330px", marginRight: "30px" }}
                      >
                        <div className="project_post style_one mr_top_20">
                          <div className="image">
                            <img
                              src="/images/projects/project-3-img.jpg"
                              className="img-fluid"
                              alt="img"
                            />
                          </div>
                          <div className="project_caro_content">
                            <div className="left_side">
                              <p>Human Resources</p>
                              <h2 className="title_pro">
                                <a href="project-details.html">
                                  Essential Steps to Writing Job Description
                                </a>
                              </h2>
                            </div>
                            <div className="right_side">
                              <a href="project-details.html">
                                <i className="icon-right-arrow"></i>
                              </a>
                              <a href="project-details.html" className="two">
                                <i className="icon-right-arrow"></i>
                              </a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div className="p_pagination">
                      <div className="swiper-pagination"></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="pd_bottom_90"></div>
        </section> */}

        <section className="call-to-action">
          <div className="call_to_action style_one">
            <div className="image">
              <img
                src="assets/images/cal-action-bg-2.jpg"
                className="img-fluid"
                alt="image"
              />
            </div>
            <div className="auto-container">
              <div className="row">
                <div className="col-lg-12">
                  <div className="left_content">
                    <div className="main_content">
                      <h1>Projets</h1>
                      <p>
                        📝 Avez-vous une idée de projet excitante que vous
                        souhaitez concrétiser ? Nous vous invitons à remplir
                        notre formulaire de soumission de projet ! Partagez-nous
                        votre vision et laissez-nous vous aider à la transformer
                        en réalité. Nous croyons en votre potentiel et sommes
                        prêts à accompagner chaque étape de votre parcours. Ne
                        manquez pas cette opportunité et rejoignez-nous dès
                        maintenant pour faire de votre projet un succès !
                      </p>
                      <div className="bottom_content">
                        <div className="button_content">
                          <a
                            href="#"
                            target="_blank"
                            rel="nofollow"
                            className="theme-btn three"
                          >
                           Remplir le formulaire
                            <i className="icon-right-arrow-long"></i>
                          </a>
                        </div>
                        <div className="call_content">
                          <span className="icon-phone-call1 icon"></span>
                          <div className="content_bx">
                            <h2>Contactez-nous</h2>
                            <p>contact@nec.cd &amp; 16599349993</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* <!---project-end---> */}

      </Layout>
    </>
  );
}
